import {test,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ExcelJS from 'exceljs';
import {createTestDatabase} from './database';
import {setTestDatabase} from '../lib/db';
import {saveEvent} from '../lib/admin';
import {seedEvents} from '../lib/seed';
import {eventReport,reportWorkbook} from '../lib/event-report';
import template from '../lib/report-template.json';
import type {User} from '../lib/types';
Object.assign(process.env,{NODE_ENV:'test'});
const pg=await createTestDatabase();
setTestDatabase({query:async(sql,values)=>(await pg.query(sql,values)) as any,transaction:fn=>pg.transaction(tx=>fn({query:async(sql,values)=>(await tx.query(sql,values)) as any}))});
after(()=>pg.close());
test('event workbook reconciles 1205 orders, couple amounts, timezones, scans and organization access',async()=>{
 await pg.exec(await readFile(new URL('../db/migrations/001_initial.sql',import.meta.url),'utf8'));await pg.exec(await readFile(new URL('../db/migrations/004_buyer_details.sql',import.meta.url),'utf8'));await pg.exec(await readFile(new URL('../db/migrations/005_checkout_holds_fees.sql',import.meta.url),'utf8'));
 await pg.query("INSERT INTO organizations VALUES('tinitix','tinitix'),('other','Other')");
 const admin:User={id:'admin',name:'Admin',email:'admin@example.test',role:'admin',verified:true,organizationId:'tinitix'};
 const event=await saveEvent({...seedEvents()[0],id:undefined},admin);
 await pg.query("INSERT INTO users(id,email,name,password_hash,verified) VALUES('admin','admin@example.test','Admin','hash',true)");
 const category=event.categories[2];
 await pg.query(`INSERT INTO orders(id,event_id,buyer_name,buyer_email,phone,status,total,people,created_at,expires_at,idempotency_key,fingerprint)
 SELECT 'order-'||n,$1,'=SUM(A1:A2)','buyer@example.test','08123456789','paid',101,2,'2026-10-06T18:30:00Z',now()+interval '1 day','key-'||n,'fingerprint' FROM generate_series(1,1205) n`,[event.id]);
 await pg.query("INSERT INTO order_items SELECT 'item-'||id,id,$1,'Couple',101,1,2 FROM orders",[category.id]);
 await pg.query("INSERT INTO payment_events(id,order_id,data,created_at) SELECT 'pay-'||id,id,'{\"status\":\"paid\",\"merchant\":\"tinitix-simulation\"}'::jsonb,'2026-10-06T18:31:00Z' FROM orders");
 await pg.query("INSERT INTO tickets(id,order_id,order_item_id,event_id,name,category_name,token_hash,ordinal) SELECT 'ticket-'||i.id||'-'||n,i.order_id,i.id,$1,'Buyer','Couple','secret-'||i.id||'-'||n,n FROM order_items i CROSS JOIN generate_series(0,1) n",[event.id]);
 await pg.query("INSERT INTO check_ins(ticket_id,user_id) VALUES('ticket-item-order-1-0','admin')");
 await pg.query("INSERT INTO orders(id,event_id,buyer_name,buyer_email,status,total,people,created_at,expires_at,idempotency_key,fingerprint) VALUES('expired',$1,'Buyer','buyer@example.test','pending',101,2,now()-interval '1 day',now()-interval '1 hour','expired-key','fp')",[event.id]);
 const report=await eventReport(admin,event.id);
 assert.equal(report.counts.orders,1206);assert.equal(report.counts.tickets,2410);assert.equal(report.counts.gross,121705);assert.equal(report.counts.pendingOrders,0);
 assert.equal(report.sheets[2].rows[0][0],'2026-10-07');assert.equal(report.sheets[2].rows[0][3],121705);
 assert.deepEqual(report.sheets[3].rows[0],['Simulation',121705,1205,2410]);
 const ticketAmount=template.Tickets.indexOf('Total Of Ticket');assert.equal(report.sheets[5].rows.reduce((sum,r)=>sum+Number(r[ticketAmount]),0),121705);
 assert.equal(report.sheets[5].rows.reduce((sum,r)=>sum+Number(r[template.Tickets.indexOf('Number Of Scanned')]),0),1);
 await assert.rejects(()=>eventReport({...admin,organizationId:'other'},event.id),/Event tidak ditemukan/);
 await assert.rejects(()=>eventReport({...admin,role:'staff'},event.id),/admin EO/);
 const bytes=await reportWorkbook(report),workbook=new ExcelJS.Workbook();await workbook.xlsx.load(bytes as any);
 assert.deepEqual(workbook.worksheets.map(s=>s.name),['Summary','Sold By Type','Sold By Date','Sold By Payment Channel','Orders','Tickets']);
 assert.equal(workbook.getWorksheet('Orders')!.rowCount,1207);assert.equal(workbook.getWorksheet('Tickets')!.rowCount,2411);
 let buyerCell:ExcelJS.Cell|undefined;workbook.getWorksheet('Orders')!.eachRow(row=>{if(row.getCell(1).value==='order-1')buyerCell=row.getCell(17);});
 assert.equal(buyerCell?.value,'=SUM(A1:A2)');assert.equal(buyerCell?.type,ExcelJS.ValueType.String);
 for(const name of ['Orders','Tickets'] as const)assert.deepEqual((workbook.getWorksheet(name)!.getRow(1).values as any[]).slice(1),template[name]);
 assert.ok(!JSON.stringify(report).includes('secret-ticket'));
});
