'use client';
import {useEffect,useState} from 'react';
import {Download,RefreshCw} from 'lucide-react';
import {api} from '@/lib/client';
import type {PublicEvent} from '@/lib/types';
import type {EventReport} from '@/lib/event-report';
import {rupiah} from '@/lib/format';

export function AdminReports({events,preview}:{events:PublicEvent[];preview:boolean}){
 const [eventId,setEventId]=useState(events[0]?.id||''),[report,setReport]=useState<EventReport|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[downloading,setDownloading]=useState(false),[tab,setTab]=useState('Summary'),[refresh,setRefresh]=useState(0);
 useEffect(()=>{if(preview||!eventId)return;let active=true;setLoading(true);setError('');setReport(null);api<EventReport>('admin/reports?eventId='+encodeURIComponent(eventId)).then(r=>{if(active)setReport(r);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[eventId,preview,refresh]);
 useEffect(()=>{if(preview)return;const timer=setInterval(()=>{if(!document.hidden)setRefresh(n=>n+1);},30000);return()=>clearInterval(timer);},[preview]);
 async function download(){setDownloading(true);setError('');try{const response=await fetch('/api/admin/reports/export?eventId='+encodeURIComponent(eventId));if(!response.ok){const body=await response.json();throw new Error(body.error||'Ekspor gagal.');}const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='export_report_'+(events.find(e=>e.id===eventId)?.slug||'event')+'.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}finally{setDownloading(false);}}
 const sheet=report?.sheets.find(s=>s.name===tab);
 return <section className="report-panel"><div className="admin-inline-form"><label className="field">Event laporan<select value={eventId} onChange={e=>setEventId(e.target.value)}>{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><button className="button button-outline" disabled={loading||preview||!eventId} onClick={()=>setRefresh(n=>n+1)}><RefreshCw size={16}/> Perbarui</button><button className="button" disabled={downloading||preview||!eventId} onClick={()=>void download()}><Download size={16}/>{downloading?'Menyiapkan Excel...':'Unduh Excel'}</button></div><p className="muted">Laporan diperbarui otomatis setiap 30 detik. Unduhan selalu mengambil transaksi terbaru untuk event yang dipilih.</p>{preview&&<div className="notice">Laporan tersedia setelah terhubung ke database.</div>}{error&&<div className="error-message" role="alert">{error}</div>}{loading&&<p role="status">Memuat laporan...</p>}{!events.length&&<p>Belum ada event untuk dilaporkan.</p>}{report&&<><div className="stat-grid">{[['Pesanan',report.counts.orders],['Tiket diterbitkan',report.counts.tickets],['Pesanan paid',report.counts.paidOrders],['Penjualan paid',rupiah(report.counts.gross)]].map(([label,value])=><div className="stat-card" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="muted">Terakhir diperbarui: {new Date(report.generatedAt).toLocaleString('id-ID',{timeZone:report.event.timezone})} ({report.event.timezone})</p><div className="report-tabs" role="group" aria-label="Sheet laporan">{report.sheets.map(s=><button key={s.name} className={tab===s.name?'button button-small':'button button-small button-outline'} aria-pressed={tab===s.name} onClick={()=>setTab(s.name)}>{s.name}</button>)}</div>{sheet&&<div className="table-scroll"><table><thead><tr>{sheet.headers.map((h,i)=><th key={i}>{h}</th>)}</tr></thead><tbody>{sheet.rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell??'—'}</td>)}</tr>)}</tbody></table>{!sheet.rows.length&&<p className="table-empty">Belum ada data pada bagian ini.</p>}</div>}<p className="muted">Pratinjau menampilkan maksimal 50 baris per sheet. Excel berisi seluruh baris.</p><div className="notice">{report.notes}</div></>}</section>;
}
