'use client';
import {useState,useEffect} from 'react';
import Link from 'next/link';
import {ArrowRight,Mail} from 'lucide-react';
import {api} from '@/lib/client';
export function AuthForm({mode}:{mode:'login'|'register'|'reset'|'access'|'confirm'}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[token,setToken]=useState(''),[kind,setKind]=useState('');
 useEffect(()=>{const params=new URLSearchParams(location.hash.slice(1));if(params.get('token')){setToken(params.get('token')!);setKind(params.get('kind')||'');history.replaceState(null,'',location.pathname);}},[]);
 const titles={login:'Welcome back.',register:'Good times ahead.',reset:'Lupa password?',access:'Tiketmu ada di sini.',confirm:'Selesaikan verifikasi.'};
 const subtitles={login:'Masuk untuk melihat semua pesananmu.',register:'Buat akun untuk menyimpan riwayat pesanan. Beli tiket tetap bisa tanpa akun.',reset:'Kami akan mengirim tautan untuk membuat password baru.',access:'Masukkan email yang digunakan saat memesan untuk menerima tautan akses aman.',confirm:'Konfirmasi email atau atur password baru untuk akunmu.'};
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{let result;if(mode==='login'){await api('auth/login',{email,password});const me=await api('auth/me');location.href=me.user?.role==='admin'?'/admin':me.user?.role==='staff'?'/check-in':'/account';return;}if(mode==='register')result=await api('auth/register',{email,password,name});if(mode==='reset')result=await api('auth/email',{email,kind:'reset'});if(mode==='access'){if(token){const r=await api('orders/exchange',{token});location.href='/orders/'+r.id;return;}result=await api('orders/access-link',{email});}if(mode==='confirm')result=await api('auth/confirm',{token,...(kind==='reset'?{password}:{})});setMessage(result?.message||'Berhasil.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="container auth-page"><div className="auth-card"><span className="eyebrow">YOUR PASS TO GOOD TIMES</span><h1>{titles[mode]}</h1><p>{subtitles[mode]}</p><form onSubmit={submit}>{mode==='register'&&<label className="field">Nama lengkap<input required minLength={2} maxLength={100} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label>}{mode!=='confirm'&&!(mode==='access'&&token)&&<label className="field">Alamat email<input type="email" required maxLength={254} autoComplete="email" placeholder="nama@email.com" value={email} onChange={e=>setEmail(e.target.value)}/></label>}{(mode==='login'||mode==='register'||(mode==='confirm'&&kind==='reset'))&&<label className="field">{mode==='confirm'?'Password baru':'Password'}<input type="password" required minLength={mode==='login'?1:10} maxLength={128} autoComplete={mode==='login'?'current-password':'new-password'} placeholder={mode==='login'?'Password akunmu':'Minimal 10 karakter'} value={password} onChange={e=>setPassword(e.target.value)}/></label>}{mode==='login'&&<Link className="text-button" href="/reset-password">Lupa password?</Link>}{error&&<div className="error-message" role="alert">{error}</div>}{message&&<p className="success-message" role="status">{message}</p>}<button className="button full" disabled={busy||(mode==='confirm'&&!token)}>{busy?'Memproses...':mode==='login'?'Masuk':mode==='register'?'Buat akun':mode==='access'&&token?'Buka pesanan':mode==='confirm'?'Konfirmasi':'Kirim tautan'} <ArrowRight size={17}/></button></form>{mode==='login'?<p className="auth-switch">Belum punya akun? <Link href="/register">Daftar</Link></p>:<p className="auth-switch"><Link href="/login">Kembali ke halaman masuk</Link></p>}{mode==='login'&&<p className="auth-switch">Beli sebagai tamu? <Link href="/access">Akses tiket via email</Link></p>}</div></div>;
}
