'use client';
import {useState,useMemo} from 'react';
import {EventSpotlight} from './event-spotlight';
import Link from 'next/link';
import {ArrowUpRight,Search,MapPin,CalendarDays,SlidersHorizontal,X,Music2,Disc3} from 'lucide-react';
import type {PublicEvent} from '@/lib/types';
import {rupiah,shortDate} from '@/lib/format';
export function Catalog({events}:{events:PublicEvent[]}){
 const [query,setQuery]=useState(''),[kinds,setKinds]=useState<string[]>([]),[city,setCity]=useState(''),[date,setDate]=useState(''),[sort,setSort]=useState('date');
 const toggleKind=(kind:string)=>setKinds(current=>current.includes(kind)?current.filter(value=>value!==kind):[...current,kind]);
 const cities=[...new Set(events.map(e=>e.city))];
 const filtered=useMemo(()=>events.filter(e=>(!kinds.length||kinds.includes(e.kind))&&(!city||e.city===city)&&(!query.trim()||(e.name+' '+e.city+' '+e.venue+' '+e.lineup.join(' ')).toLowerCase().includes(query.trim().toLowerCase()))&&(!date||new Date(e.starts)<=new Date(Date.now()+Number(date)*86400000))).sort((a,b)=>sort==='price'?(a.startingPrice??Infinity)-(b.startingPrice??Infinity):Date.parse(a.starts)-Date.parse(b.starts)),[events,kinds,city,query,date,sort]);
 const reset=()=>{setQuery('');setKinds([]);setCity('');setDate('');};
 return <div className="discovery discovery-refresh"><section className="discover-masthead"><div className="container"><p className="hero-kicker">Konser, dance floor, dan kamu.</p><h1>Temukan event berikutnya.</h1><form className="discover-search" role="search" onSubmit={e=>{e.preventDefault();document.getElementById('events')?.scrollIntoView({behavior:'instant'});}}><Search size={24}/><label className="sr-only" htmlFor="event-search">Cari nama event atau lokasi</label><input id="event-search" type="search" placeholder="Cari nama event, lokasi, atau artis..." value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button type="button" className="icon-button" onClick={()=>setQuery('')} aria-label="Hapus pencarian"><X size={18}/></button>}<button className="button" type="submit">Cari event <ArrowUpRight size={18}/></button></form></div></section>
 <div className="container discovery-highlights"><EventSpotlight events={events}/><Link href="/organizer/services" className="organizer-promo"><div className="organizer-promo-art"><span className="wordmark">tinitix</span><h2>Event organizer?</h2><p>Panggungmu.<br/>Penontonmu.<br/>Kami urus tiketnya.</p></div><div className="organizer-promo-link"><span>Kenali teknologi event kami</span><ArrowUpRight size={26}/></div></Link></div>
 <section className="container event-section" id="events"><div className="section-heading"><h2>Semua event<span className="blue-text">.</span></h2></div>
 <div className="filter-bar discovery-refinements"><label className="filter-select"><MapPin size={18}/><span className="sr-only">Filter kota</span><select value={city} onChange={e=>setCity(e.target.value)}><option value="">Semua kota</option>{cities.map(c=><option key={c}>{c}</option>)}</select></label><label className="filter-select"><CalendarDays size={18}/><span className="sr-only">Filter tanggal</span><select value={date} onChange={e=>setDate(e.target.value)}><option value="">Semua tanggal</option><option value="7">7 hari ke depan</option><option value="30">30 hari ke depan</option><option value="90">90 hari ke depan</option></select></label></div>
 <p className="category-hint">Pilih satu atau beberapa kategori untuk menemukan rencanamu.</p><div className="event-toolbar"><div className="tabs category-pills" role="group" aria-label="Kategori event"><button aria-pressed={!kinds.length} onClick={()=>setKinds([])} className={!kinds.length?'tab active':'tab'}>Semua Event<span>{events.length}</span></button>{(['Konser','Party'] as const).map(k=><button key={k} aria-pressed={kinds.includes(k)} onClick={()=>toggleKind(k)} className={kinds.includes(k)?'tab active':'tab'}>{k==='Konser'?<Music2 size={16}/>:<Disc3 size={16}/>}<span>{k}</span></button>)}</div><label className="sort-control"><SlidersHorizontal size={15}/><span className="sr-only">Urutkan event</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="date">Tanggal terdekat</option><option value="price">Harga terendah</option></select></label></div>
 <div className="catalog-results"><p role="status"><strong>{filtered.length} event</strong> ditemukan</p>{(query||city||date||kinds.length>0)&&<button className="text-button" onClick={reset}>Reset semua <X size={14}/></button>}</div>
 {(query||city||date||kinds.length>0)&&<div className="active-filters" aria-label="Filter aktif">{query&&<button onClick={()=>setQuery('')} aria-label="Hapus filter pencarian">Pencarian: {query}<X size={14}/></button>}{kinds.map(kind=><button key={kind} onClick={()=>toggleKind(kind)} aria-label={'Hapus kategori '+kind}>{kind}<X size={14}/></button>)}{city&&<button onClick={()=>setCity('')} aria-label="Hapus filter kota">{city}<X size={14}/></button>}{date&&<button onClick={()=>setDate('')} aria-label="Hapus filter tanggal">{date} hari ke depan<X size={14}/></button>}</div>}
 {filtered.length?<div className="event-grid">{filtered.map(e=><Link href={'/events/'+e.slug} key={e.id} className="event-card"><div className="poster-wrap"><img src={e.poster} alt={'Poster '+e.name} width="900" height="700" loading="lazy"/></div><div className="card-info"><div className="card-date"><span>{e.kind}</span><span>{shortDate(e.starts,e.timezone)}</span></div><h3>{e.name}</h3><p className="card-lineup">{e.lineup.join(" / ")}</p><p className="card-location">{e.venue}, {e.city}</p><div className="card-bottom"><div><span className="price-label">{e.startingPrice!==null?'Mulai dari':e.saleState}</span>{e.startingPrice!==null&&<strong>{rupiah(e.startingPrice)}{e.startingPeople===2&&<small> / paket 2 orang</small>}</strong>}</div><span className="card-cta">Lihat event <ArrowUpRight size={16}/></span></div></div></Link>)}</div>:<div className="empty-state"><Search size={36}/><h3>{events.length?'Belum ketemu yang cocok?':'Panggung berikutnya segera hadir.'}</h3><p>{events.length?'Coba kata kunci atau filter lain. Malam serumu mungkin ada di sana.':'Event baru akan muncul di sini saat sudah diumumkan.'}</p>{events.length>0&&<button className="button" onClick={reset}>Hapus filter</button>}</div>}
 <div className="catalog-count">Menampilkan {filtered.length} dari {events.length} event <a href="#events">Kembali ke pencarian &uarr;</a></div></section>
 <section className="container booking-note"><h2>Sudah punya rencana?</h2><div><p>Tiket tersimpan di email. Buka kembali kapan pun, termasuk saat sudah di depan pintu venue.</p><Link href="/access" className="text-link">Temukan tiket saya <ArrowUpRight size={18}/></Link></div></section></div>;
}
