'use client';
import {useState,useMemo} from 'react';
import Link from 'next/link';
import {ArrowUpRight,Search,MapPin,CalendarDays,SlidersHorizontal,X,Music2,Disc3} from 'lucide-react';
import type {PublicEvent} from '@/lib/types';
import {rupiah,shortDate} from '@/lib/format';
export function Catalog({events}:{events:PublicEvent[]}){
 const [query,setQuery]=useState(''),[kind,setKind]=useState('Semua Event'),[city,setCity]=useState(''),[date,setDate]=useState(''),[sort,setSort]=useState('date');
 const cities=[...new Set(events.map(e=>e.city))];
 const filtered=useMemo(()=>events.filter(e=>(kind==='Semua Event'||e.kind===kind)&&(!city||e.city===city)&&(!query||(e.name+' '+e.city+' '+e.venue+' '+e.lineup.join(' ')).toLowerCase().includes(query.toLowerCase()))&&(!date||new Date(e.starts)<=new Date(Date.now()+Number(date)*86400000))).sort((a,b)=>sort==='price'?(a.startingPrice??Infinity)-(b.startingPrice??Infinity):Date.parse(a.starts)-Date.parse(b.starts)),[events,kind,city,query,date,sort]);
 const reset=()=>{setQuery('');setKind('Semua Event');setCity('');setDate('');};
 const featured=events[0];
 return <div className="discovery"><section className="editorial-hero container">
 <div className="editorial-intro"><p className="hero-kicker">Konser, dance floor, dan kamu.</p><h1>Ada malam<br/>yang <em>ditunggu.</em></h1><div className="hero-bottom"><p>Temukan panggung berikutnya.<br/>Pilih tiket, ajak teman, berangkat.</p><a href="#events" className="button">Cari event <ArrowUpRight size={19}/></a></div></div>
 {featured&&<Link className="featured-event" href={'/events/'+featured.slug} aria-label={'Lihat event '+featured.name}><div className="featured-poster"><img src={featured.poster} alt={'Poster '+featured.name} width="900" height="700" fetchPriority="high"/></div><div className="featured-caption"><div><span>Agenda terdekat / {featured.city}</span><h2>{featured.name}</h2><p>{shortDate(featured.starts,featured.timezone)} &middot; {featured.venue}</p></div><ArrowUpRight size={30}/></div></Link>}
 </section>
 <section className="container event-section" id="events"><div className="section-heading"><h2>Di kalender berikutnya<span className="blue-text">.</span></h2></div>
 <div className="filter-bar"><label className="search-field"><Search size={20}/><span className="sr-only">Cari nama event atau lokasi</span><input placeholder="Cari event, artis, atau kota..." value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon-button" onClick={()=>setQuery('')} aria-label="Hapus pencarian"><X size={17}/></button>}</label><label className="filter-select"><MapPin size={18}/><span className="sr-only">Filter kota</span><select value={city} onChange={e=>setCity(e.target.value)}><option value="">Semua kota</option>{cities.map(c=><option key={c}>{c}</option>)}</select></label><label className="filter-select"><CalendarDays size={18}/><span className="sr-only">Filter tanggal</span><select value={date} onChange={e=>setDate(e.target.value)}><option value="">Semua tanggal</option><option value="7">7 hari ke depan</option><option value="30">30 hari ke depan</option><option value="90">90 hari ke depan</option></select></label></div>
 <div className="event-toolbar"><div className="tabs" aria-label="Kategori event">{['Semua Event','Konser','Party'].map((k,i)=><button key={k} aria-pressed={kind===k} onClick={()=>setKind(k)} className={kind===k?'tab active':'tab'}>{i===1?<Music2 size={16}/>:i===2?<Disc3 size={16}/>:null}{k}{i===0&&<span>{events.length}</span>}</button>)}</div><label className="sort-control"><SlidersHorizontal size={15}/><span className="sr-only">Urutkan event</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="date">Tanggal terdekat</option><option value="price">Harga terendah</option></select></label></div>
 <div className="catalog-results"><p role="status"><strong>{filtered.length} event</strong> ditemukan</p>{(query||city||date||kind!=='Semua Event')&&<button className="text-button" onClick={reset}>Reset semua <X size={14}/></button>}</div>
 {(query||city||date||kind!=='Semua Event')&&<div className="active-filters" aria-label="Filter aktif">{query&&<button onClick={()=>setQuery('')} aria-label="Hapus filter pencarian">Pencarian: {query}<X size={14}/></button>}{kind!=='Semua Event'&&<button onClick={()=>setKind('Semua Event')} aria-label="Hapus filter kategori">{kind}<X size={14}/></button>}{city&&<button onClick={()=>setCity('')} aria-label="Hapus filter kota">{city}<X size={14}/></button>}{date&&<button onClick={()=>setDate('')} aria-label="Hapus filter tanggal">{date} hari ke depan<X size={14}/></button>}</div>}
 {filtered.length?<div className="event-grid">{filtered.map(e=><Link href={'/events/'+e.slug} key={e.id} className="event-card"><div className="poster-wrap"><img src={e.poster} alt={'Poster '+e.name} width="900" height="700" loading="lazy"/></div><div className="card-info"><div className="card-date"><span>{e.kind}</span><span>{shortDate(e.starts,e.timezone)}</span></div><h3>{e.name}</h3><p className="card-lineup">{e.lineup.join(" / ")}</p><p className="card-location">{e.venue}, {e.city}</p><div className="card-bottom"><div><span className="price-label">{e.startingPrice!==null?'Mulai dari':e.saleState}</span>{e.startingPrice!==null&&<strong>{rupiah(e.startingPrice)}{e.startingPeople===2&&<small> / paket 2 orang</small>}</strong>}</div><span className="card-cta">Lihat event <ArrowUpRight size={16}/></span></div></div></Link>)}</div>:<div className="empty-state"><Search size={36}/><h3>{events.length?'Belum ketemu yang cocok?':'Panggung berikutnya segera hadir.'}</h3><p>{events.length?'Coba kata kunci atau filter lain. Malam serumu mungkin ada di sana.':'Event baru akan muncul di sini saat sudah diumumkan.'}</p>{events.length>0&&<button className="button" onClick={reset}>Hapus filter</button>}</div>}
 <div className="catalog-count">Menampilkan {filtered.length} dari {events.length} event <a href="#events">Kembali ke pencarian &uarr;</a></div></section>
 <section className="container booking-note"><h2>Sudah punya rencana?</h2><div><p>Tiket tersimpan di email. Buka kembali kapan pun, termasuk saat sudah di depan pintu venue.</p><Link href="/access" className="text-link">Temukan tiket saya <ArrowUpRight size={18}/></Link></div></section></div>;
}
