'use client';
import {useState,useEffect,useRef} from 'react';
import Link from 'next/link';
import {Camera,ScanLine,CheckCircle,AlertCircle,Square} from 'lucide-react';
import {api} from '@/lib/client';
import type {Event} from '@/lib/types';
export function CheckIn(){
 const [events,setEvents]=useState<Event[]>([]),[eventId,setEventId]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[camera,setCamera]=useState(false);
 const video=useRef<HTMLVideoElement>(null),controls=useRef<{stop:()=>void}|null>(null),scanning=useRef(false);
 useEffect(()=>{api<Event[]>('admin/staff-events').then(e=>{setEvents(e);setEventId(e[0]?.id||'');}).catch(e=>setError(e.message));return()=>controls.current?.stop();},[]);
 const stop=()=>{controls.current?.stop();controls.current=null;setCamera(false);scanning.current=false;};
 async function submit(raw=code){if(!eventId||scanning.current)return;scanning.current=true;setBusy(true);setError('');setResult(null);try{setResult(await api('admin/check-ins',{eventId,token:raw.trim()}));setCode('');}catch(e){setError((e as Error).message+' Tiket belum terverifikasi.');}finally{setBusy(false);scanning.current=false;}}
 async function startCamera(){setError('');setResult(null);setCamera(true);try{const {BrowserQRCodeReader}=await import('@zxing/browser');const reader=new BrowserQRCodeReader();controls.current=await reader.decodeFromVideoDevice(undefined,video.current!,async(result)=>{if(result&&!scanning.current){controls.current?.stop();setCamera(false);await submit(result.getText());}});}catch{setError('Kamera tidak dapat diakses. Izinkan kamera atau masukkan kode QR secara manual.');stop();}}
 return <div className="container checkin-page"><div className="section-heading"><div><span className="eyebrow blue-text">AT THE DOOR</span><h1>Check-in event.</h1></div><Link href="/admin" className="text-link">Dashboard ↗</Link></div><div className="checkin-grid"><section className="form-panel"><label className="field">Event penugasan<select value={eventId} onChange={e=>{stop();setEventId(e.target.value);setResult(null);}}><option value="" disabled>Pilih event</option>{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><div className="scanner-view"><video ref={video} autoPlay muted playsInline className={camera?'':'hidden-video'}/>{!camera&&<div><ScanLine size={68}/><h2>Siap menyambut?</h2><p>Arahkan kamera ke QR pada e-ticket.</p></div>}</div><button className="button full" disabled={!eventId||busy} onClick={camera?stop:startCamera}>{camera?<><Square size={17}/> Hentikan kamera</>:<><Camera size={18}/> Aktifkan kamera</>}</button><form className="manual-scan" onSubmit={e=>{e.preventDefault();void submit();}}><label className="field">Atau masukkan kode dari QR<input required minLength={20} value={code} onChange={e=>setCode(e.target.value)} autoComplete="off" placeholder="Tempel isi QR, bukan ID pesanan"/></label><button className="button button-outline full" disabled={!eventId||busy}>{busy?'Memverifikasi...':'Validasi tiket'}</button></form></section><section><div className="notice">Petugas hanya dapat memindai event yang ditugaskan. Validasi membutuhkan koneksi internet; pesan koneksi terputus bukan bukti tiket valid.</div>{error&&<div className="error-message" role="alert">{error}</div>}{result&&<div className={'scan-result '+result.result} role="status">{result.result==='valid'?<CheckCircle size={48}/>:<AlertCircle size={48}/>}<h2>{result.message}</h2>{result.name&&<p>{result.name}<br/>{result.category}</p>}{result.at&&<small>{new Date(result.at).toLocaleString('id-ID')}</small>}</div>}{!events.length&&<Link className="button button-outline" href="/login">Masuk sebagai petugas</Link>}</section></div></div>;
}
