'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowLeft,ArrowRight,Minus,Plus,Ticket,ShieldCheck,Mail,Info,Check,ChevronRight} from 'lucide-react';
import type {PublicEvent} from '@/lib/types';
import {rupiah,dateLabel,shortDate} from '@/lib/format';
import {api} from '@/lib/client';
export function Checkout({initialEvent,enabled}:{initialEvent:PublicEvent;enabled:boolean}){
 const [event,setEvent]=useState(initialEvent),[quantities,setQuantities]=useState<Record<string,number>>({}),[form,setForm]=useState({buyerName:'',buyerEmail:'',confirmEmail:'',phone:'',accepted:false}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[review,setReview]=useState(false),[touched,setTouched]=useState<Record<string,boolean>>({});
 const router=useRouter(),key=useRef('');
 const selected=event.categories.filter(c=>quantities[c.id]>0),total=selected.reduce((s,c)=>s+c.price*quantities[c.id],0),people=selected.reduce((s,c)=>s+c.people*quantities[c.id],0);
 const validEmail=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.buyerEmail);
 const valid=people>0&&people<=event.maxPeople&&form.buyerName.trim().length>=2&&validEmail&&form.buyerEmail.trim().toLowerCase()===form.confirmEmail.trim().toLowerCase()&&form.accepted&&selected.every(c=>c.state==='available'&&quantities[c.id]<=c.available)&&event.saleState==='Tersedia';
 useEffect(()=>{key.current='';},[quantities,form]);
 function change(id:string,delta:number){setQuantities(q=>({...q,[id]:Math.max(0,(q[id]||0)+delta)}));setError('');}
 async function submit(e:React.FormEvent){e.preventDefault();if(!valid||busy||!enabled)return;setBusy(true);setError('');key.current ||=crypto.randomUUID();try{const result=await api<{id:string}>('orders',{...form,eventId:event.id,items:selected.map(c=>({categoryId:c.id,quantity:quantities[c.id],price:c.price}))},{'Idempotency-Key':key.current});router.push('/orders/'+result.id);}catch(e){const err=e as Error&{code?:string};setError(err.message);if(err.code==='STOCK_CHANGED'||err.code==='PRICE_CHANGED'){try{setEvent(await api<PublicEvent>('events/'+event.slug));setReview(true);key.current='';}catch{}}setBusy(false);}}
 const update=(name:string,value:string|boolean)=>setForm(f=>({...f,[name]:value}));
 return <div className="container checkout-page"><Link className="back-link" href={'/events/'+event.slug}><ArrowLeft size={17}/> Kembali ke event</Link><div className="checkout-heading"><div><span className="eyebrow">ONE STEP CLOSER TO THE GOOD TIMES</span><h1>Pilih tiketmu<span className="blue-text">.</span></h1></div><div className="checkout-steps"><span className="active"><b>1</b> Pilih tiket</span><ChevronRight size={16}/><span><b>2</b> Pembayaran</span><ChevronRight size={16}/><span><b>3</b> E-ticket</span></div></div>
 {!enabled&&<div className="notice"><Info size={20}/><span><strong>Checkout belum diaktifkan.</strong> Kamu tetap dapat mencoba pemilihan tiket. Transaksi menunggu konfigurasi database dan provider pembayaran.</span></div>}
 <form onSubmit={submit} className="checkout-grid"><div><section className="form-panel"><div className="panel-heading"><h2>Kategori tiket</h2><span>Maks. {event.maxPeople} orang / pesanan</span></div><div className="category-list">{event.categories.map(c=>{const disabled=c.state!=='available'||event.saleState!=='Tersedia';return <div className={'category-row '+(disabled?'unavailable':'')} key={c.id}><div className="category-icon"><Ticket size={22}/></div><div className="category-content"><div className="category-name"><h3>{c.name}</h3><span className={'status-dot '+c.state}>{({available:'Tersedia',soon:'Segera dijual',soldout:'Habis',ended:'Penjualan berakhir'})[c.state]}</span></div><p>{c.people===2?'1 paket untuk 2 orang · 2 QR berbeda':'1 tiket untuk 1 orang'}</p><small>{shortDate(c.starts,event.timezone)} — {shortDate(c.ends,event.timezone)}</small><strong>{rupiah(c.price)} <span>/ {c.people===2?'paket':'tiket'}</span></strong></div><div className="quantity-control"><button type="button" disabled={!quantities[c.id]||busy} onClick={()=>change(c.id,-1)} aria-label={'Kurangi '+c.name}><Minus size={16}/></button><output aria-label={'Jumlah '+c.name}>{quantities[c.id]||0}</output><button type="button" disabled={disabled||busy||people+c.people>event.maxPeople||(quantities[c.id]||0)>=c.available} onClick={()=>change(c.id,1)} aria-label={'Tambah '+c.name}><Plus size={16}/></button></div></div>;})}</div><p className="form-footnote"><Info size={15}/> Tiket couple dapat dipakai oleh dua orang yang datang terpisah.</p></section>
 <section className="form-panel buyer-form"><div className="panel-heading"><h2>Data pembeli</h2><span>Tidak perlu membuat akun</span></div><p>E-ticket akan dikirim ke email ini. Pastikan tidak ada salah ketik, ya.</p><div className="field-grid"><label className="field wide">Nama lengkap <span>*</span><input required autoComplete="name" minLength={2} maxLength={100} placeholder="Sesuai nama pembeli" value={form.buyerName} onChange={e=>update('buyerName',e.target.value)} onBlur={()=>setTouched(t=>({...t,name:true}))}/>{touched.name&&form.buyerName.trim().length<2&&<small className="field-error">Isi nama lengkap, minimal 2 karakter.</small>}</label><label className="field">Alamat email <span>*</span><input type="email" required autoComplete="email" maxLength={254} placeholder="nama@email.com" value={form.buyerEmail} onChange={e=>update('buyerEmail',e.target.value)} onBlur={()=>setTouched(t=>({...t,email:true}))}/>{touched.email&&!validEmail&&<small className="field-error">Masukkan alamat email yang valid.</small>}</label><label className="field">Konfirmasi email <span>*</span><input type="email" required autoComplete="off" placeholder="Ketik ulang alamat email" value={form.confirmEmail} onChange={e=>update('confirmEmail',e.target.value)} onBlur={()=>setTouched(t=>({...t,confirm:true}))}/>{touched.confirm&&form.confirmEmail.toLowerCase()!==form.buyerEmail.toLowerCase()&&<small className="field-error">Alamat email belum sama.</small>}</label><label className="field wide">Nomor WhatsApp <small>(opsional)</small><input type="tel" autoComplete="tel" maxLength={25} pattern="[+0-9 ()-]*" placeholder="+62" value={form.phone} onChange={e=>update('phone',e.target.value)}/></label></div></section></div>
 <aside><div className="order-summary"><h2>Ringkasan pesanan</h2><div className="summary-event"><img src={event.poster} alt="" width="82" height="74"/><div><h3>{event.name}</h3><p>{dateLabel(event.starts,event.timezone)}</p><small>{event.venue}, {event.city}</small></div></div><div className="summary-items">{selected.length?selected.map(c=><div key={c.id}><span>{c.name}<small>{quantities[c.id]} {c.people===2?'paket':'tiket'} × {rupiah(c.price)}</small></span><strong>{rupiah(c.price*quantities[c.id])}</strong></div>):<p className="muted">Belum ada tiket dipilih.</p>}</div><div className="summary-people"><Ticket size={17}/>{people} orang · {selected.reduce((s,c)=>s+quantities[c.id],0)} unit pembelian</div><div className="cost-row"><span>Subtotal</span><span>{rupiah(total)}</span></div><div className="cost-row"><span>Biaya admin</span><span>{rupiah(0)}</span></div><div className="summary-total" aria-live="polite"><span>Total pembayaran</span><strong>{rupiah(total)}</strong></div>{form.buyerEmail&&<div className="email-confirm"><Mail size={16}/><span>Tiket dikirim ke<br/><strong>{form.buyerEmail}</strong></span></div>}<label className="checkbox-field"><input type="checkbox" required checked={form.accepted} onChange={e=>update('accepted',e.target.checked)}/><span>Saya telah memeriksa email dan menyetujui <Link href={'/events/'+event.slug} target="_blank">syarat event</Link> serta <Link href="/privacy" target="_blank">kebijakan privasi</Link>.</span></label>{error&&<div className="error-message" role="alert">{error}</div>}{review&&<div className="notice compact"><span>Ringkasan telah diperbarui. Periksa harga dan jumlah tiket.</span><button type="button" className="text-button" onClick={()=>{setReview(false);setError('');}}>Sudah saya periksa <Check size={16}/></button></div>}<button className="button full" type="submit" disabled={!valid||busy||!enabled||review}>{busy?'Memproses...':'Checkout'} <ArrowRight size={18}/></button><p className="secure-note"><ShieldCheck size={16}/> Stok ditahan 15 menit setelah checkout.</p></div></aside></form></div>;
}
