'use client';
import {useState} from 'react';
import '@/app/organizer/overview.css';
import Link from 'next/link';
import {Wallet,Ticket,ReceiptText,Upload,List,Table2,Info,X} from 'lucide-react';

import type {EoLiveData} from '@/lib/eo-live';
const number=(n:number)=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
export function EoOverview({base,data}:{base:string;data:EoLiveData}){
 const tickets=data.categories;
 const percent=(n:number)=>data.capacity?Math.round(n/data.capacity*100):0;
 const soldPercent=percent(data.paidPeople);
 const [table,setTable]=useState(false),[breakdown,setBreakdown]=useState(false),[notice,setNotice]=useState('');
 return <div className="eo-overview">
  <div className="ov-toolbar"><div><div className="ov-updated">Terakhir diperbarui: {new Date(data.updatedAt).toLocaleString('id-ID',{timeZone:data.timezone})}</div><span className="ov-demo">Transaksi tersimpan · termasuk pembayaran simulasi jika digunakan</span></div><a className="ov-primary ov-export" href={'/api/admin/reports/export?eventId='+encodeURIComponent(data.eventId)}><Upload size={22}/> Export Report</a></div>
  {notice&&<div className="ov-notice" role="status">{notice}<button aria-label="Tutup pemberitahuan" onClick={()=>setNotice('')}><X size={17}/></button></div>}
  <div className="ov-grid">
   <section className="ov-card ov-payout"><div className="ov-metric-head"><div><h2>Pendapatan tiket (IDR)</h2><strong>{number(data.revenue.subtotal)}</strong></div><span className="ov-icon"><Wallet/></span></div><div className="ov-payout-actions"><button className="ov-outline" aria-expanded={breakdown} onClick={()=>setBreakdown(!breakdown)}>Sales Breakdown</button><button className="ov-primary" onClick={()=>setNotice('Pencairan dana belum tersedia. Pendapatan ini bukan saldo yang dapat dicairkan.')}>Request Payout</button></div>{breakdown&&<dl className="ov-breakdown"><dt>Subtotal tiket</dt><dd>{number(data.revenue.subtotal)}</dd><dt>Pajak</dt><dd>{number(data.revenue.tax)}</dd><dt>Biaya layanan</dt><dd>{number(data.revenue.service)}</dd><dt>Total pembayaran berhasil</dt><dd>{number(data.revenue.gross)}</dd></dl>}</section>
   <section className="ov-card ov-metrics"><div className="ov-sold"><div className="ov-metric-head"><div><h2>Total Tickets Sold</h2><strong>{data.paidPeople} <small>/ {data.capacity}</small></strong></div><span className="ov-icon"><Ticket/></span></div><p>View <Link href={base+'?view=sales'}>Sales Trend</Link></p></div><div className="ov-average"><div className="ov-metric-head"><div><h2>Average Tickets / Order <Info size={15} aria-label="Jumlah tiket rata-rata per pesanan"/></h2><strong>{data.paidOrders?(data.paidPeople/data.paidOrders).toFixed(1):'0'}</strong></div><span className="ov-icon"><ReceiptText/></span></div></div></section>
   <section className="ov-card ov-summary"><h2>Total Summary</h2><div className="ov-donut" role="img" aria-label={`${data.paidPeople} dari ${data.capacity} tiket terjual`} style={{background:`conic-gradient(var(--ov-paid) 0 ${Math.min(100,soldPercent)}%,#edf1f6 ${Math.min(100,soldPercent)}% 100%)`}}><div><strong>{soldPercent}%</strong><span>{data.paidPeople}/{data.capacity}</span></div></div><dl className="ov-summary-legend">{[{name:'Paid',value:`${data.paidPeople} (${percent(data.paidPeople)}%)`,color:'paid'},{name:'Reserved',value:`${data.pendingPeople} (${percent(data.pendingPeople)}%)`,color:'pending'},{name:'Available',value:`${data.availablePeople} (${percent(data.availablePeople)}%)`,color:'available'}].map(s=><div key={s.name}><dt><i className={s.color}/>{s.name}</dt><dd>{s.value}</dd></div>)}</dl></section>
   <section className="ov-card ov-ticket-status"><header><div><h2>Ticket Type Status</h2><p style={{fontSize:11}}>Kuota per unit; paket couple = 2 orang. Stok tersedia mengikuti kapasitas venue bersama.</p><div className="ov-status-legend"><span><i className="paid"/>Paid</span><span><i className="pending"/>Pending</span></div></div><div className="ov-view-toggle" aria-label="Tampilan status tiket"><button aria-label="Tampilan daftar" aria-pressed={!table} onClick={()=>setTable(false)}><List size={22}/></button><button aria-label="Tampilan tabel" aria-pressed={table} onClick={()=>setTable(true)}><Table2 size={21}/></button></div></header><div className="ov-ticket-scroll" tabIndex={0} aria-label="Status semua jenis tiket">{table?<table><thead><tr><th>Ticket Type</th><th>Paid</th><th>Pending</th><th>Available</th></tr></thead><tbody>{tickets.map(t=><tr key={t.id}><td>{t.name}<small>{number(t.price)} IDR</small></td><td>{t.paid}</td><td>{t.pending}</td><td>{t.available}</td></tr>)}</tbody></table>:tickets.map(t=><div className="ov-ticket-row" key={t.id}><div><h3>{t.name}</h3><p>{number(t.price)} IDR</p></div><div className="ov-ticket-progress"><div className="ov-track" role="progressbar" aria-label={t.name} aria-valuenow={t.paid} aria-valuemin={0} aria-valuemax={t.capacity}><span style={{width:((t.capacity?t.paid/t.capacity*100:0))+'%'}}/></div><span><b>{Math.round((t.capacity?t.paid/t.capacity*100:0))}%</b><small>{t.paid} / {t.capacity} unit</small><small>{t.pending} reservasi · {t.available} tersedia</small></span></div></div>)}</div></section>
  </div>
 </div>;
}
