'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api} from '@/lib/client';
import type {User} from '@/lib/types';
export function OrganizerRegister(){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 useEffect(()=>{api<{user:User|null}>('auth/me').then(r=>setUser(r.user)).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const data=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{if(user){await api('organizer/create',data);window.location.assign('/admin?create=event');}else{const result=await api('auth/organizer-register',data);setMessage(result.message);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="container auth-page"><section className="auth-card"><span className="eyebrow">TINITIX ORGANIZER</span><h1>Buat ruang untuk event kamu.</h1><p>Daftarkan organisasi sendiri. Akses pengelolaan event aktif setelah email terverifikasi.</p>{loading?<p>Memuat akun...</p>:user?.role==='admin'?<Link className="button" href="/admin">Buka dashboard organizer</Link>:user&&!user.verified?<><p>Verifikasi email akun kamu sebelum membuat organisasi.</p><button className="button" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await api('auth/email',{email:user.email,kind:'verify'});setMessage(r.message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Kirim ulang verifikasi</button><p>Setelah verifikasi, muat ulang halaman ini.</p></>:user?.role==='staff'?<p>Akun ini terhubung sebagai petugas. Gunakan akun lain untuk membuat organisasi.</p>:message?<p role="status">{message}</p>:<form onSubmit={submit}>{!user&&<><label className="field">Nama lengkap<input name="name" required minLength={2} maxLength={100} autoComplete="name"/></label><label className="field">Alamat email<input name="email" type="email" required maxLength={254} autoComplete="email"/></label><label className="field">Password<input name="password" type="password" required minLength={10} maxLength={128} autoComplete="new-password"/><small>Minimal 10 karakter.</small></label></>}<label className="field">Nama organisasi<input name="organizationName" required minLength={2} maxLength={120} autoComplete="organization"/></label><label><input type="checkbox" required/> Saya menyetujui <Link href="/terms">syarat layanan</Link> dan <Link href="/privacy">kebijakan privasi</Link>.</label><button className="button full" disabled={busy}>{busy?'Memproses...':user?'Buat organisasi':'Daftar organizer'}</button></form>}{error&&<p className="error-message" role="alert">{error}</p>}{message&&user&&<p role="status">{message}</p>}<p className="auth-switch">Sudah punya akun? <Link href="/organizer/login">Login Organizer</Link></p></section></div>;
}
