'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowRight,Eye,EyeOff,Ticket,ScanLine,BarChart3} from 'lucide-react';
import {api} from '@/lib/client';
export function OrganizerLogin(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(event:React.FormEvent){
  event.preventDefault();if(busy)return;setBusy(true);setError('');
  try{
   await api('auth/login',{email,password});
   const {user}=await api<{user:{role:string;verified:boolean}|null}>('auth/me');
   if(user?.role!=='admin'||!user.verified){setError('Akun ini belum memiliki akses admin organizer. Hubungi pengelola Tinitix untuk mengaktifkan akses organizer.');setBusy(false);return;}
   window.location.assign('/admin?create=event');
  }catch(e){setError((e as Error).message);setBusy(false);}
 }
 return <div className="organizer-login-page"><section className="organizer-login-visual" aria-label="Selamat datang di Tinitix Organizer"><img className="organizer-login-photo" src="/images/organizer-concert.jpg" alt="" fetchPriority="high"/><div className="organizer-login-shade"/><div className="organizer-login-welcome"><span className="eyebrow">TINITIX FOR ORGANIZERS</span><h1>Welcome.</h1><p>Setiap momen besar dimulai dari kamu.<br/>Bawa idemu ke panggung bersama Tinitix.</p><div className="organizer-login-features"><span><Ticket size={23}/> Ticketing</span><span><ScanLine size={23}/> Check-in</span><span><BarChart3 size={23}/> Event reports</span></div></div><span className="organizer-login-caption">YOUR EVENT. THEIR NEXT GOOD TIME.</span></section><section className="organizer-login-panel" aria-labelledby="organizer-login-title"><div className="organizer-login-form"><span className="eyebrow blue-text">CREATOR ACCESS</span><h2 id="organizer-login-title">Login</h2><p className="organizer-login-intro">Masuk untuk membuat event dan mengelola acara kamu.</p><p className="organizer-login-terms">Dengan masuk, kamu menyetujui <Link href="/terms">Syarat & Ketentuan</Link> dan <Link href="/privacy">Kebijakan Privasi</Link> Tinitix.</p><form onSubmit={submit} aria-busy={busy}><label className="field">Email <span aria-hidden="true">*</span><input type="email" required autoComplete="email" maxLength={254} placeholder="Masukkan email" value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></label><label className="field">Password <span aria-hidden="true">*</span><div className="organizer-password"><input type={visible?'text':'password'} required autoComplete="current-password" maxLength={128} placeholder="Masukkan password" value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/><button type="button" aria-label={visible?'Sembunyikan password':'Tampilkan password'} aria-pressed={visible} onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff size={21}/>:<Eye size={21}/>}</button></div></label><div className="organizer-login-recovery"><Link href="/reset-password">Lupa password?</Link></div>{error&&<div className="error-message" role="alert">{error}</div>}<button className="button full organizer-login-submit" type="submit" disabled={busy}>{busy?'Memproses...':'Log In'} <ArrowRight size={19}/></button></form><p className="organizer-login-signup">Belum punya akun? <Link href="/register">Sign Up</Link></p><div className="organizer-login-help"><p>Akses membuat event tersedia untuk akun admin organizer.</p><Link href="/organizer/help-center">Bantuan akun organizer <ArrowRight size={15}/></Link></div></div></section></div>;
}
