'use client';
import Link from 'next/link';
import {useState,useEffect,useRef} from 'react';
import {ArrowUpRight,Menu,X,ArrowRight,Ticket} from 'lucide-react';
export function Logo(){return <Link href="/" className="wordmark" aria-label="tinitix beranda">tinitix<span className="logo-dot">.</span></Link>;}
export function Header({demo}:{demo:boolean}){
 const menuButton=useRef<HTMLButtonElement>(null);
 const [open,setOpen]=useState(false),[user,setUser]=useState<{name:string;role:string}|null>(null);
 useEffect(()=>{if(!demo)fetch('/api/auth/me').then(r=>r.json()).then(r=>setUser(r.user)).catch(()=>{});},[demo]);
 useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape'){setOpen(false);menuButton.current?.focus();}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[open]);
 return <><a className="skip-link" href="#main">Lewati ke konten</a>{demo&&<div className="preview-banner">Mode pratinjau <span>&middot; Event contoh. Tidak ada penjualan tiket nyata.</span></div>}<header className="site-header"><div className="container nav-wrap"><Logo/><nav id="primary-navigation" className={open?'main-nav open':'main-nav'} aria-label="Navigasi utama"><Link href="/#events" onClick={()=>setOpen(false)}>Jelajahi Event</Link><Link href="/help" onClick={()=>setOpen(false)}>Cara Pesan</Link><Link href="/access" onClick={()=>setOpen(false)}>Tiket Saya</Link></nav><div className="auth-nav">{user?<><Link href={user.role==='admin'?'/admin':user.role==='staff'?'/check-in':'/account'} className="login-link">{user.name.split(' ')[0]} <ArrowUpRight size={16}/></Link><button className="text-button" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});location.href='/';}}>Keluar</button></>:<><Link className="login-link" href="/login">Masuk</Link><Link className="button button-small" href="/register">Daftar <ArrowUpRight size={16}/></Link></>}<button ref={menuButton} aria-controls="primary-navigation" className="mobile-menu icon-button" onClick={()=>setOpen(!open)} aria-label={open?'Tutup menu':'Buka menu'} aria-expanded={open}>{open?<X/>:<Menu/>}</button></div></div></header></>;
}
export function Footer(){return <footer className="site-footer"><div className="container footer-editorial"><div><Logo/><p>Ketemu di depan panggung.</p></div><nav aria-label="Navigasi footer"><Link href="/help">Panduan pemesanan</Link><Link href="/help#support">Hubungi kami</Link><Link href="/access">Tiket saya</Link></nav></div><div className="container footer-bottom"><span>&copy; {new Date().getFullYear()} tinitix</span><div><Link href="/terms">Syarat & ketentuan</Link><Link href="/privacy">Kebijakan privasi</Link></div></div></footer>;}
export function EmptyState({title,description,href,label}:{title:string;description:string;href?:string;label?:string}){return <div className="empty-state"><Ticket size={38}/><h2>{title}</h2><p>{description}</p>{href&&<Link className="button" href={href}>{label||'Jelajahi event'} <ArrowRight size={18}/></Link>}</div>;}
