import {z} from 'zod';
import {database,transaction,type Db} from './db';
import {loadEvent,usedStock,publicEvent} from './catalog';
import {AppError,id,hash,audit} from './security';
import type {Event,User} from './types';
const iso=z.string().refine(v=>Number.isFinite(Date.parse(v)),'Tanggal tidak valid.');
const categorySchema=z.object({id:z.string().max(100),name:z.string().min(2).max(100),price:z.number().int().min(0).max(100000000),quota:z.number().int().min(0).max(1000000),people:z.union([z.literal(1),z.literal(2)]),starts:iso,ends:iso}).refine(c=>Date.parse(c.ends)>Date.parse(c.starts),'Akhir penjualan harus sesudah awal.');
export const eventSchema=z.object({id:z.string().max(100).optional(),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).min(3).max(100),name:z.string().trim().min(3).max(120),kind:z.enum(['Konser','Party']),city:z.string().min(2).max(80),venue:z.string().min(2).max(120),address:z.string().max(300),starts:iso,ends:iso,timezone:z.enum(['Asia/Jakarta','Asia/Makassar','Asia/Jayapura']),status:z.enum(['draft','published','closed','cancelled']),taxPercent:z.number().min(0).max(100).multipleOf(0.01).default(10),servicePercent:z.number().min(0).max(100).multipleOf(0.01).default(3),capacity:z.number().int().min(1).max(1000000),maxPeople:z.number().int().min(1).max(50),poster:z.string().max(500).refine(v=>v.startsWith('/posters/')||/^https:\/\/[^/]+\.public\.blob\.vercel-storage\.com\//.test(v),'Gunakan poster yang diunggah ke Vercel Blob.'),banner:z.string().max(500).refine(v=>!v||v.startsWith('/posters/')||/^https:\/\/[^/]+\.public\.blob\.vercel-storage\.com\//.test(v),'Gunakan banner yang diunggah ke Vercel Blob.').optional(),theme:z.string().max(50).default('midnight'),eyebrow:z.string().max(100).default('LIVE WITH TINITIX'),lineup:z.array(z.string().max(100)).max(40),description:z.string().min(20).max(10000),terms:z.string().min(20).max(10000),categories:z.array(categorySchema).length(5)}).refine(e=>Date.parse(e.ends)>Date.parse(e.starts),'Waktu selesai harus setelah mulai.');
export async function saveEvent(input:unknown,user:User){
 const parsed=eventSchema.parse(input);
 if(parsed.categories.some((c,i)=>c.people!==([1,1,2,1,2][i])||Date.parse(c.ends)>Date.parse(parsed.ends)))throw new AppError(400,'Urutan kategori harus Early Bird, Single, Couple, Single, Couple. Periode jual tidak boleh melewati akhir event.');
 return transaction(async db=>{
  const eventId=parsed.id||id('event');let old:Event|undefined;
  if(parsed.id){old=await loadEvent(db,eventId,true);if(old.organizationId!==user.organizationId)throw new AppError(403,'Akses tidak diizinkan.');}
  const used=old?await usedStock(db,eventId):{};
  if(old&&old.categories.some(c=>(used[c.id]||0)>0&&!parsed.categories.some(n=>n.id===c.id)))throw new AppError(409,'Kategori dengan penjualan atau reservasi tidak dapat dihapus.');
  const categories=parsed.categories.map((c,i)=>({...c,id:old?.categories.some(o=>o.id===c.id)?c.id:eventId+'-cat-'+i}));
  if(categories.some(c=>(used[c.id]||0)>c.quota))throw new AppError(409,'Kuota tidak boleh lebih kecil dari stok yang terpakai.');
  if(old&&categories.some(c=>{const previous=old?.categories.find(o=>o.id===c.id);return previous&&(used[c.id]||0)>0&&previous.people!==c.people;}))throw new AppError(409,'Jumlah orang pada kategori terjual tidak boleh diubah.');
  const occupied=categories.reduce((n,c)=>n+(used[c.id]||0)*c.people,0);if(parsed.capacity<occupied)throw new AppError(409,'Kapasitas di bawah tiket dan reservasi aktif.');
  if(old&&parsed.status==='draft'&&(await db.query('SELECT id FROM orders WHERE event_id=$1 LIMIT 1',[eventId])).rows.length)throw new AppError(409,'Event dengan pesanan tidak dapat kembali ke draft.');
  const event:Event={...parsed,id:eventId,organizationId:user.organizationId,categories};
  const {categories:_,...data}=event;
  await db.query('INSERT INTO events(id,organization_id,slug,data) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO UPDATE SET slug=EXCLUDED.slug,data=EXCLUDED.data',[eventId,user.organizationId,event.slug,JSON.stringify(data)]);
  for(const c of categories)await db.query('INSERT INTO categories(id,event_id,name,price,quota,people,starts_at,ends_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,price=EXCLUDED.price,quota=EXCLUDED.quota,people=EXCLUDED.people,starts_at=EXCLUDED.starts_at,ends_at=EXCLUDED.ends_at',[c.id,eventId,c.name,c.price,c.quota,c.people,c.starts,c.ends]);
  await audit(db,user.id,'event_saved',eventId,event.status);return event;
 });
}
export async function adminOverview(user:User){
 const db=database();const er=await db.query('SELECT id FROM events WHERE organization_id=$1 ORDER BY data->>\'starts\'',[user.organizationId]);
 const events=await Promise.all(er.rows.map(async r=>{const e=await loadEvent(db,r.id);return publicEvent(e,await usedStock(db,e.id));}));
 const stats=(await db.query("SELECT COUNT(*) FILTER(WHERE o.status='paid')::int AS paid,COALESCE(SUM(o.total) FILTER(WHERE o.status='paid'),0)::bigint AS revenue,COALESCE(SUM(o.people) FILTER(WHERE o.status='paid'),0)::int AS people,COUNT(*) FILTER(WHERE o.status='pending' AND o.expires_at>now())::int AS reserved FROM orders o JOIN events e ON e.id=o.event_id WHERE e.organization_id=$1",[user.organizationId])).rows[0];
 const checkins=(await db.query('SELECT COUNT(*)::int AS count FROM check_ins c JOIN tickets t ON t.id=c.ticket_id JOIN events e ON e.id=t.event_id WHERE e.organization_id=$1',[user.organizationId])).rows[0].count;
 const logs=(await db.query("SELECT a.* FROM audit_logs a WHERE a.actor=$1 OR a.target IN (SELECT id FROM events WHERE organization_id=$2) OR a.target IN (SELECT o.id FROM orders o JOIN events e ON e.id=o.event_id WHERE e.organization_id=$2) ORDER BY a.created_at DESC LIMIT 30",[user.id,user.organizationId])).rows;
 return {events,orders:[],stats:{...stats,revenue:Number(stats.revenue),checkins},logs};
}
export async function staffEvents(user:User){const r=await database().query(user.role==='admin'?'SELECT id FROM events WHERE organization_id=$1':'SELECT e.id FROM events e JOIN assignments a ON a.event_id=e.id WHERE e.organization_id=$1 AND a.user_id=$2',user.role==='admin'?[user.organizationId]:[user.organizationId,user.id]);return Promise.all(r.rows.map(e=>loadEvent(database(),e.id)));}
export async function canScan(db:Db,user:User,eventId:string){const e=await loadEvent(db,eventId);if(e.organizationId!==user.organizationId)throw new AppError(403,'Event tidak ditugaskan ke akun ini.');if(user.role==='admin')return e;if(user.role!=='staff'||!(await db.query('SELECT 1 FROM assignments WHERE event_id=$1 AND user_id=$2',[eventId,user.id])).rows.length)throw new AppError(403,'Event tidak ditugaskan ke akun ini.');return e;}
export async function checkIn(input:unknown,user:User){const body=z.object({eventId:z.string(),token:z.string().min(20).max(150)}).parse(input);return transaction(async db=>{const event=await canScan(db,user,body.eventId);const ticket=(await db.query('SELECT * FROM tickets WHERE token_hash=$1 FOR UPDATE',[hash(body.token)])).rows[0];if(!ticket)return {result:'not_found',message:'Tiket tidak ditemukan.'};if(ticket.event_id!==body.eventId)return {result:'wrong_event',message:'Tiket untuk event lain.'};if(event.status==='cancelled'||new Date(event.ends)<=new Date()||ticket.status==='cancelled')return {result:'cancelled',message:'Tiket dibatalkan atau event telah selesai.'};const scan=(await db.query('SELECT checked_at FROM check_ins WHERE ticket_id=$1',[ticket.id])).rows[0];if(scan)return {result:'already_used',message:'Tiket sudah digunakan.',at:scan.checked_at};const result=await db.query('INSERT INTO check_ins(ticket_id,user_id) VALUES($1,$2) ON CONFLICT(ticket_id) DO NOTHING RETURNING checked_at',[ticket.id,user.id]);if(!result.rows[0])return {result:'already_used',message:'Tiket sudah digunakan.'};await audit(db,user.id,'check_in',ticket.id);return {result:'valid',message:'Tiket valid. Selamat menikmati!',name:ticket.name,category:ticket.category_name,at:result.rows[0].checked_at};});}
export async function assignStaff(input:unknown,user:User){const body=z.object({email:z.string().email().transform(v=>v.toLowerCase()),eventIds:z.array(z.string()).max(100)}).parse(input);return transaction(async db=>{const staff=(await db.query('SELECT u.id,m.role,m.organization_id FROM users u JOIN memberships m ON u.id=m.user_id WHERE u.email=$1 FOR UPDATE OF m',[body.email])).rows[0];if(!staff||staff.role==='admin'||staff.organization_id!==user.organizationId)throw new AppError(400,'Gunakan email akun pembeli/petugas yang terdaftar pada organisasi ini.');for(const e of body.eventIds){const event=await loadEvent(db,e);if(event.organizationId!==user.organizationId)throw new AppError(403,'Akses event ditolak.');}await db.query("UPDATE memberships SET role='staff' WHERE user_id=$1",[staff.id]);await db.query('DELETE FROM assignments WHERE user_id=$1',[staff.id]);for(const e of new Set(body.eventIds))await db.query('INSERT INTO assignments(user_id,event_id) VALUES($1,$2)',[staff.id,e]);await audit(db,user.id,'staff_assigned',staff.id);return {message:'Penugasan petugas disimpan.'};});}
export async function cancelTicket(input:unknown,user:User){const body=z.object({ticketId:z.string(),reason:z.string().trim().min(10).max(500)}).parse(input);return transaction(async db=>{const t=(await db.query('SELECT t.id,e.organization_id FROM tickets t JOIN events e ON e.id=t.event_id WHERE t.id=$1',[body.ticketId])).rows[0];if(!t||t.organization_id!==user.organizationId)throw new AppError(404,'Tiket tidak ditemukan.');await db.query("UPDATE tickets SET status='cancelled' WHERE id=$1",[t.id]);await audit(db,user.id,'ticket_cancelled',t.id,body.reason);return {message:'Tiket dibatalkan. Pembayaran/refund tetap ditangani manual.'};});}
