import {z} from 'zod';
import {database,transaction,type Db} from './db';
import {AppError,id,token,hash,passwordHash,passwordValid,audit} from './security';
import {enqueueMail} from './mail';
import {appUrl} from './config';
import type {User} from './types';
const emailSchema=z.string().trim().email().max(254).transform(v=>v.toLowerCase());
const passwordSchema=z.string().min(10,'Password minimal 10 karakter.').max(128);
export async function currentUser(session?:string):Promise<User|null>{
 if(!session)return null;
 const r=await database().query('SELECT u.id,u.email,u.name,u.verified,m.role,m.organization_id FROM sessions s JOIN users u ON u.id=s.user_id JOIN memberships m ON m.user_id=u.id WHERE s.token_hash=$1 AND s.expires_at>now()',[hash(session)]);const u=r.rows[0];return u?{id:u.id,email:u.email,name:u.name,verified:u.verified,role:u.role,organizationId:u.organization_id}:null;
}
export async function requireRole(session:string|undefined,roles:User['role'][]){const u=await currentUser(session);if(!u||!u.verified||!roles.includes(u.role))throw new AppError(403,'Akses tidak diizinkan. Silakan masuk dengan akun yang sesuai.');return u;}
export async function newSession(db:Db,userId:string){const raw=token();await db.query('INSERT INTO sessions(token_hash,user_id,expires_at) VALUES($1,$2,$3)',[hash(raw),userId,new Date(Date.now()+86400000)]);return raw;}
export async function login(input:unknown){const body=z.object({email:emailSchema,password:z.string().max(128)}).parse(input);const r=await database().query('SELECT * FROM users WHERE email=$1',[body.email]);const user=r.rows[0];const valid=passwordValid(body.password,user?.password_hash||passwordHash('dummy-invalid-password'));if(!user||!valid)throw new AppError(401,'Email atau password tidak sesuai.');return {session:await newSession(database(),user.id)};}
export async function register(input:unknown){const body=z.object({name:z.string().trim().min(2).max(100),email:emailSchema,password:passwordSchema}).parse(input);await transaction(async db=>{const u=id('user');const result=await db.query('INSERT INTO users(id,email,name,password_hash) VALUES($1,$2,$3,$4) ON CONFLICT(email) DO NOTHING RETURNING id',[u,body.email,body.name,passwordHash(body.password)]);if(!result.rows[0])return;await db.query("INSERT INTO memberships(user_id,organization_id,role) VALUES($1,'tinitix','buyer')",[u]);await authEmail(db,u,body.email,'verify');});return {message:'Jika alamat dapat didaftarkan, tautan verifikasi akan dikirim ke email tersebut.'};}
async function authEmail(db:Db,userId:string,email:string,kind:'verify'|'reset'){const raw=token();await db.query('INSERT INTO auth_tokens(token_hash,user_id,kind,expires_at) VALUES($1,$2,$3,$4)',[hash(raw),userId,kind,new Date(Date.now()+3600000)]);await enqueueMail(db,email,{subject:(kind==='verify'?'Verifikasi email':'Reset password')+' — tinitix',text:`Buka tautan berikut dalam 1 jam:\n${appUrl()}/auth/confirm#token=${raw}&kind=${kind}\nAbaikan jika Anda tidak meminta ini.`});}
export async function requestAuthEmail(input:unknown){const body=z.object({email:emailSchema,kind:z.enum(['reset','verify'])}).parse(input);await transaction(async db=>{const r=await db.query('SELECT id FROM users WHERE email=$1',[body.email]);if(r.rows[0])await authEmail(db,r.rows[0].id,body.email,body.kind);});return {message:'Jika alamat terdaftar, tautan akan dikirim ke email tersebut.'};}
export async function confirmAuth(input:unknown){const body=z.object({token:z.string().min(30).max(100),password:passwordSchema.optional()}).parse(input);return transaction(async db=>{const r=await db.query('DELETE FROM auth_tokens WHERE token_hash=$1 AND expires_at>now() RETURNING *',[hash(body.token)]);const t=r.rows[0];if(!t)throw new AppError(400,'Tautan tidak valid atau sudah kedaluwarsa.');if(t.kind==='reset'){if(!body.password)throw new AppError(400,'Masukkan password baru.');await db.query('UPDATE users SET password_hash=$1 WHERE id=$2',[passwordHash(body.password),t.user_id]);await db.query('DELETE FROM sessions WHERE user_id=$1',[t.user_id]);await db.query("DELETE FROM auth_tokens WHERE user_id=$1 AND kind='reset'",[t.user_id]);}else await db.query('UPDATE users SET verified=true WHERE id=$1',[t.user_id]);await audit(db,t.user_id,t.kind,t.user_id);return {message:t.kind==='reset'?'Password diperbarui. Silakan masuk.':'Email terverifikasi. Silakan masuk.'};});}
