import type {Event} from './types';
export const ORGANIZATION = 'tinitix';
const start = (day:number, hour=19) => `2026-11-${String(day).padStart(2,'0')}T${String(hour).padStart(2,'0')}:00:00+07:00`;
const base = {organizationId:ORGANIZATION,timezone:'Asia/Jakarta',status:'published' as const,capacity:1500,maxPeople:6,address:'Informasi venue demo. Konfirmasi lokasi sebelum event nyata.',terms:'Event demonstrasi, bukan penjualan tiket nyata. Tiket berlaku untuk satu kali masuk. Satu paket couple berisi dua tiket yang dapat digunakan terpisah. Dilarang membawa senjata dan barang berbahaya. Ikuti arahan petugas serta ketentuan venue.',description:'Satu panggung, banyak cerita. Nikmati malam penuh musik, energi, dan momen yang layak dikenang bersama orang-orang favoritmu. Pintu dibuka satu jam sebelum acara. Detail lineup dan jadwal dapat berubah; informasi terbaru akan disampaikan oleh penyelenggara.'};
const records = [
 {id:'ev-midnight',slug:'midnight-frequency',name:'Midnight Frequency',kind:'Party',city:'Jakarta',venue:'The Pallas, SCBD',starts:start(7,20),ends:start(8,2),poster:'/posters/midnight.svg',theme:'midnight',eyebrow:'AFTER DARK. ALL TOGETHER.',lineup:['DISKORIA','PRONTAXAN','FEEL KOPLO'],price:150000},
 {id:'ev-soundscape',slug:'soundscape-festival',name:'Soundscape Festival 2026',kind:'Konser',city:'Bandung',venue:'Lapangan PPI Pussenif',starts:start(14,16),ends:start(14,23),poster:'/posters/soundscape.svg',theme:'soundscape',eyebrow:'A LITTLE LOUDER. A LITTLE CLOSER.',lineup:['HINDIA','REALITY CLUB','.FEAST'],price:225000},
 {id:'ev-afterhours',slug:'after-hours-vol-03',name:'After Hours Vol. 03',kind:'Party',city:'Jakarta',venue:'Bengkel Space, SCBD',starts:start(21,21),ends:start(22,3),poster:'/posters/afterhours.svg',theme:'afterhours',eyebrow:'LEAVE THE DAY BEHIND.',lineup:['DIPHA BARUS','W.W','RBA'],price:175000},
 {id:'ev-sunset',slug:'sunset-sessions',name:'Sunset Sessions',kind:'Konser',city:'Bali',venue:'Bali Beach Garden',starts:start(22,16),ends:start(22,22),poster:'/posters/sunset.svg',theme:'sunset',eyebrow:'GOOD MUSIC. GOLDEN HOUR.',lineup:['KUNTO AJI','SAL PRIADI','DANILLA'],price:200000},
 {id:'ev-electric',slug:'electric-weekend',name:'Electric Weekend',kind:'Party',city:'Surabaya',venue:'Grand City Surabaya',starts:start(28,19),ends:start(29,1),poster:'/posters/electric.svg',theme:'electric',eyebrow:'TURN YOUR WEEKEND UP.',lineup:['WEIRD GENIUS','SIHK','JEVIN JULIAN'],price:185000},
 {id:'ev-blue',slug:'blue-room-live',name:'Blue Room Live',kind:'Konser',city:'Bandung',venue:'Critical 11',starts:start(29,18),ends:start(29,23),poster:'/posters/blue.svg',theme:'blue',eyebrow:'UP CLOSE. ALL HEART.',lineup:['BERNADYA','NADIN AMIZAH','JUICY LUICY'],price:125000},
] as const;
export function seedEvents():Event[] { return records.map((r,index)=>{const {price,...record}=r; return {...base,...record,banner:record.poster.replace('.svg','-banner.svg'),lineup:[...r.lineup],categories:[{name:'Early Bird',people:1,price,quota:100},{name:'Presale 1 Single Ticket',people:1,price:price+50000,quota:300},{name:'Presale 1 Couple Ticket',people:2,price:price*2+50000,quota:150},{name:'Presale 2 Single Ticket',people:1,price:price+100000,quota:300},{name:'Presale 2 Couple Ticket',people:2,price:price*2+150000,quota:200}].map((c,i)=>({...c,id:`${r.id}-cat-${i}`,starts:i>2?'2026-10-25T00:00:00+07:00':'2026-01-01T00:00:00+07:00',ends:r.starts,...(index===2&&i===0?{quota:0}:{})}))};}); }
