import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {chromium,expect} from '@playwright/test';
import sharp from 'sharp';
import ExcelJS from 'exceljs';
import zxing from '@zxing/library';
const {QRCodeReader,BinaryBitmap,HybridBinarizer,RGBLuminanceSource,DecodeHintType}=zxing;

const base=process.env.STAGING_URL;
if(base!=='https://tinitix-staging-preview.vercel.app'||process.env.STAGING_QA_CONFIRM!=='run')throw Error('Explicit staging-only opt-in required');
const adminEmail=process.env.STAGING_ADMIN_EMAIL,adminPassword=process.env.STAGING_ADMIN_PASSWORD,testerEmail=process.env.STAGING_TESTER_EMAIL,bypass=process.env.STAGING_BYPASS;
if(!adminEmail||!adminPassword||!testerEmail||!bypass)throw Error('Staging credentials and tester email required');
const headers={'x-vercel-protection-bypass':bypass,Origin:base};
const stamp=Date.now(),slug='qa-acceptance-'+stamp;
const result={startedAt:new Date().toISOString(),slug,checks:[],eventId:null,orderIds:[],physicalPhones:'not-tested'};
await fs.mkdir('.vercel/staging-qa',{recursive:true});
const output='.vercel/staging-qa/result-'+stamp+'.json';
const browser=await chromium.launch({headless:true});
let event,admin,stage='initialization';
const record=(name,details={})=>{result.checks.push({name,passed:true,...details});console.log(JSON.stringify({check:name,passed:true,...details}));};
async function context(){const c=await browser.newContext({baseURL:base,viewport:{width:1440,height:1000}});c.setDefaultTimeout(30000);await c.route('**/*',route=>new URL(route.request().url()).origin===base?route.continue({headers:{...route.request().headers(),'x-vercel-protection-bypass':bypass}}):route.continue());return c;}
async function call(c,path,data,extra={}){return data===undefined?c.request.get(base+path,{headers,...extra}):c.request.post(base+path,{headers,data,...extra});}
async function body(r,expected=200){assert.equal(r.status(),expected,'Unexpected HTTP status '+r.url().split('?')[0]);return r.json();}
async function saveEditor(page,editor){const responsePromise=page.waitForResponse(r=>r.url()===base+'/api/admin/events'&&r.request().method()==='POST');await editor.getByRole('button',{name:'Simpan event',exact:true}).click();const r=await responsePromise;if(r.status()!==200){const message=await r.json();throw Error('Save event HTTP '+r.status()+': '+message.error);}const e=await r.json();await expect(editor).toBeHidden();return e;}
// Exact PNG decoding verifies encoded content; camera detection remains a separate physical test.
async function decode(ticket){const {data,info}=await sharp(Buffer.from(ticket.qr.split(',')[1],'base64')).removeAlpha().greyscale().raw().toBuffer({resolveWithObject:true});return new QRCodeReader().decode(new BinaryBitmap(new HybridBinarizer(new RGBLuminanceSource(new Uint8ClampedArray(data),info.width,info.height))),new Map([[DecodeHintType.PURE_BARCODE,true]])).getText();}
try{
 admin=await context();const page=await admin.newPage();stage='admin login';await page.goto(base+'/login');await page.getByLabel('Alamat email',{exact:true}).fill(adminEmail);await page.getByLabel('Password',{exact:true}).fill(adminPassword);const loginResponse=page.waitForResponse(r=>r.url()===base+'/api/auth/login');await page.getByRole('button',{name:'Masuk',exact:true}).click();await body(await loginResponse);await expect(page.getByRole('heading',{name:'Semua dalam kendali.'})).toBeVisible({timeout:30000});record('admin-login');
 stage='create draft and upload artwork';await page.getByRole('button',{name:'Buat event',exact:true}).click();let editor=page.getByRole('dialog');await editor.getByLabel('Nama event',{exact:true}).fill('QA Acceptance '+stamp);await editor.getByLabel('Slug URL').fill(slug);await editor.getByLabel('Nama venue').fill('QA Venue');await editor.getByLabel('Alamat lengkap').fill('Event khusus uji staging, bukan penjualan umum');await editor.getByLabel('Deskripsi',{exact:true}).fill('Event QA khusus penerimaan admin, stok, laporan, dan check-in staging.');await editor.getByLabel('Syarat event',{exact:false}).fill('Tiket simulasi pengujian, tidak berlaku untuk event nyata atau penjualan umum.');
 const prices=[10001,20001,35001,25001,45001];
 for(let i=0;i<5;i++){await editor.getByLabel('Harga per unit (IDR)').nth(i).fill(String(prices[i]));await editor.getByLabel('Kuota unit',{exact:true}).nth(i).fill(i===0?'1':i===2?'2':'0');}
 for(const [index,width,height,color] of [[0,900,700,'#1746ff'],[1,1440,450,'#111827']]){const image=await sharp({create:{width,height,channels:3,background:color}}).png().toBuffer();const responsePromise=page.waitForResponse(r=>r.url()===base+'/api/admin/poster');await editor.locator('input[type=file]').nth(index).setInputFiles({name:index?'qa-banner.png':'qa-poster.png',mimeType:'image/png',buffer:image});const uploaded=await body(await responsePromise);assert.match(uploaded.url,/\.public\.blob\.vercel-storage\.com\//);record(index?'banner-upload':'poster-upload');}
 event=await saveEditor(page,editor);result.eventId=event.id;assert.equal((await call(admin,'/api/events/'+event.id)).status(),404);record('draft-hidden');
 stage='edit draft and publish';await page.getByRole('button',{name:'Event',exact:true}).click();await page.getByRole('button',{name:'Edit '+event.name,exact:true}).click();editor=page.getByRole('dialog');await editor.getByLabel('Nama venue').fill('QA Venue Updated');await editor.getByRole('combobox',{name:'Status',exact:true}).selectOption('published');event=await saveEditor(page,editor);assert.equal(event.venue,'QA Venue Updated');const catalog=await body(await call(admin,'/api/events'));assert(catalog.some(e=>e.id===event.id));record('edit-publish-catalog');
 stage='published event artwork';const publicPage=await admin.newPage();await publicPage.goto(base+'/events/'+slug);await expect.poll(()=>publicPage.locator('img').evaluateAll((imgs,urls)=>urls.every(url=>imgs.some(img=>img.src===url&&img.complete&&img.naturalWidth>0)),[event.poster,event.banner]),{timeout:30000}).toBe(true);record('public-poster-banner');
 stage='guest couple checkout';const guest=await context(),buyer=await guest.newPage();await buyer.goto(base+'/events/'+slug+'/tickets');await buyer.getByRole('button',{name:'Tambah Presale 1 Couple Ticket',exact:true}).click();await buyer.getByLabel('Nama lengkap').fill('QA Couple Tester');await buyer.getByLabel('Alamat email',{exact:false}).fill(testerEmail);await buyer.getByLabel('Konfirmasi email').fill(testerEmail);await buyer.getByRole('checkbox').check();await buyer.getByRole('button',{name:'Checkout',exact:true}).click();await expect(buyer).toHaveURL(/\/orders\/TIX/,{timeout:30000});const coupleId=buyer.url().split('/').pop();result.orderIds.push(coupleId);await buyer.getByRole('button',{name:'Simulasikan pembayaran sukses'}).click();await expect(buyer.locator('.issued-ticket')).toHaveCount(2,{timeout:30000});const couple=await body(await call(guest,'/api/orders/'+coupleId));assert.equal(couple.total,35001);assert.equal(couple.status,'paid');const codes=await Promise.all(couple.tickets.map(decode));assert.equal(new Set(codes).size,2);record('couple-checkout-two-readable-qr');
 stage='scan race two sessions';const staffA=await context(),staffB=await context();for(const c of [staffA,staffB])await body(await call(c,'/api/auth/login',{email:adminEmail,password:adminPassword}));const scans=await Promise.all([staffA,staffB].map(c=>call(c,'/api/admin/check-ins',{eventId:event.id,token:codes[0]}).then(r=>body(r))));assert.deepEqual(scans.map(s=>s.result).sort(),['already_used','valid']);record('simultaneous-same-qr-one-valid');
 const scanPage=await staffB.newPage();await scanPage.goto(base+'/check-in');await scanPage.getByLabel('Event penugasan').selectOption(event.id);await scanPage.getByLabel('Atau masukkan kode dari QR').fill(codes[1]);await scanPage.getByRole('button',{name:'Validasi tiket',exact:true}).click();await expect(scanPage.getByRole('status')).toContainText('Tiket valid.');await scanPage.getByLabel('Atau masukkan kode dari QR').fill(codes[1]);await scanPage.getByRole('button',{name:'Validasi tiket',exact:true}).click();await expect(scanPage.getByRole('status')).toContainText('Tiket sudah digunakan.');record('second-qr-valid-repeat-rejected-ui');
 stage='final stock race';const a=await context(),b=await context(),early=event.categories.find(c=>c.name==='Early Bird');const checkout={eventId:event.id,buyerName:'QA Final Stock',buyerEmail:testerEmail,confirmEmail:testerEmail,accepted:true,items:[{categoryId:early.id,quantity:1,price:early.price}]};const raced=await Promise.all([a,b].map(async c=>({context:c,response:await call(c,'/api/orders',checkout,{headers:{...headers,'idempotency-key':randomUUID()}})})));assert.deepEqual(raced.map(r=>r.response.status()).sort(),[201,409]);const winner=raced.find(r=>r.response.status()===201),winnerOrder=await winner.response.json();result.orderIds.push(winnerOrder.id);const payments=await Promise.all([call(winner.context,'/api/orders/'+winnerOrder.id+'/simulate',{status:'paid'}),call(winner.context,'/api/orders/'+winnerOrder.id+'/simulate',{status:'paid'})]);assert(payments.some(p=>p.status()===200));for(const p of payments){assert([200,409].includes(p.status()));if(p.status()===409)assert.equal((await p.json()).error,'Pesanan tidak dapat dibayar.');else await body(p);}const single=await body(await call(winner.context,'/api/orders/'+winnerOrder.id));assert.equal(single.tickets.length,1);const stock=await body(await call(admin,'/api/events/'+event.id));assert.equal(stock.categories.find(c=>c.id===early.id).available,0);record('last-stock-one-winner-duplicate-payment-one-ticket',{checkoutStatuses:raced.map(r=>r.response.status()).sort(),paymentStatuses:payments.map(p=>p.status()).sort()});
 stage='quota protection';const canonical={...event,categories:[...event.categories].sort((a,b)=>Number(a.id.split('-').pop())-Number(b.id.split('-').pop()))};const invalid={...canonical,categories:canonical.categories.map(c=>c.name==='Presale 1 Couple Ticket'?{...c,quota:0}:c)};assert.equal((await call(admin,'/api/admin/events',invalid)).status(),409);record('cannot-reduce-quota-below-sales');
 stage='reports reconciliation';const report=await body(await call(admin,'/api/admin/reports?eventId='+event.id));assert.equal(report.counts.orders,2);assert.equal(report.counts.paidOrders,2);assert.equal(report.counts.tickets,3);assert.equal(report.counts.gross,45002);await page.goto(base+'/admin');await page.getByRole('button',{name:'Laporan Excel',exact:true}).click();const reportLoaded=page.waitForResponse(r=>r.url().includes('/api/admin/reports?')&&new URL(r.url()).searchParams.get('eventId')===event.id);await page.getByLabel('Event laporan').selectOption(event.id);await body(await reportLoaded);await expect(page.getByRole('button',{name:'Unduh Excel',exact:true})).toBeEnabled();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Unduh Excel',exact:true}).click();const download=await downloadPromise,w=new ExcelJS.Workbook();await w.xlsx.readFile(await download.path());assert.equal(w.worksheets.length,6);const rows=name=>{const s=w.getWorksheet(name),heads=s.getRow(1).values;return Array.from({length:s.rowCount-1},(_,i)=>Object.fromEntries(heads.slice(1).map((h,j)=>[h,s.getRow(i+2).getCell(j+1).value])));};const orders=rows('Orders'),tickets=rows('Tickets');assert.equal(orders.length,2);assert.equal(tickets.length,3);assert.equal(orders.reduce((n,r)=>n+r['Total Of Order'],0),45002);assert.equal(tickets.reduce((n,r)=>n+r['Total Of Ticket'],0),45002);assert.equal(tickets.reduce((n,r)=>n+r['Number Of Scanned'],0),2);for(const sheet of ['Sold By Date','Sold By Payment Channel'])assert.equal(rows(sheet).reduce((n,r)=>n+r[sheet==='Sold By Payment Channel'?'TotalAmount':'Total Amount'],0),45002);assert.equal(rows('Sold By Type').reduce((n,r)=>n+r['Paid'],0),3);const summary=rows('Summary');assert.equal(summary.find(r=>r.Items==='Gross Ticket Sales')['Total Amount'],45002);assert.equal(summary.find(r=>r.Items==='Paid Ticket')['Total Amount'],3);record('six-sheet-excel-reconciles',{paidOrders:2,tickets:3,gross:45002,checkIns:2});
 stage='order search';await page.getByRole('button',{name:'Pesanan',exact:true}).click();await page.getByLabel('Cari pesanan').fill(coupleId);await expect(page.locator('tbody tr')).toHaveCount(1);record('admin-order-search');
 result.passed=true;
}catch(error){result.passed=false;result.failedStage=stage;result.failure=String(error.message||error.constructor.name).split('Call log:')[0];console.error(JSON.stringify({stage,error:result.failure}));process.exitCode=1;}
finally{
 if(event&&admin){try{const closed={...event,status:'closed',categories:[...event.categories].sort((a,b)=>Number(a.id.split('-').pop())-Number(b.id.split('-').pop()))};const r=await call(admin,'/api/admin/events',closed);result.qaEventClosed=r.status()===200;console.log(JSON.stringify({qaEventClosed:result.qaEventClosed}));}catch{result.qaEventClosed=false;}}
 result.finishedAt=new Date().toISOString();await fs.writeFile(output,JSON.stringify(result,null,2));console.log('Evidence: '+output);await browser.close();
}
